### ISSUE TITLE
Can you add Gaussian blur to the image at your convenience?

### ISSUE THREAD

**Issue by Zhangxxl** [igr/sexyeditor#16]
Gaussian blur is very beautiful;

**Comment by igr** [comment]
It could be possible - but then again, you might do the same on the image using some 3rd party image processing tool, probably with much better result. I am afraid if I add this option, then many other options would come, like making image BW, adjusting some colors etc. Plus, we would need to save for each image these settings.

So it would be much better to make your background anyway you like it before adding it to the plugin :))
